#!/bin/bash

# Colors
bg='282828' bgl='3c3836' fg='ebdbb2'
red='fb4934' green='b8bb26' yellow='fabd2f'
blue='83a598' magenta='d3869b' cyan='8ec07c'
alpha='00000000'

# CMD
swaylock -f \
	`# General` \
	--ignore-empty-password \
	--show-failed-attempts \
	--hide-keyboard-layout \
	--indicator-caps-lock \
	`# Appearance - change CC to your desired transparency` \
	--color ${bg}FF \
	`#--image ${IMAGE} --scaling fill` \
	--font 'CaskaydiaCove Nerd Font Mono' --font-size 30 \
	`# Backspace Key` \
	--key-hl-color ${green} \
	--caps-lock-key-hl-color ${blue} \
	--bs-hl-color ${red} \
	--caps-lock-bs-hl-color ${red} \
	`# Indicator` \
	--indicator-radius 120 \
	--indicator-thickness 10 \
	`# Inside Circle Colors` \
	--inside-color ${alpha} \
	--inside-clear-color ${alpha} \
	--inside-caps-lock-color ${alpha} \
	--inside-ver-color ${blue} \
	--inside-wrong-color ${red} \
	`# Layout Colors` \
	--layout-bg-color ${cyan} \
	--layout-border-color ${cyan} \
	--layout-text-color ${bg} \
	`# Line Colors` \
	--line-color ${bg} \
	--line-clear-color ${red} \
	--line-caps-lock-color ${bg} \
	--line-ver-color ${bg} \
	--line-wrong-color ${bg} \
	`# Ring Colors` \
	--ring-color ${cyan} \
	--ring-clear-color ${bg} \
	--ring-caps-lock-color ${magenta} \
	--ring-ver-color ${blue} \
	--ring-wrong-color ${red} \
	`# Separator Color` \
	--separator-color ${bg} \
	`# Text Colors` \
	--text-color ${fg} \
	--text-clear-color ${fg} \
	--text-caps-lock-color ${fg} \
	--text-ver-color ${bg} \
	--text-wrong-color ${bg} \
	--indicator-caps-lock
