name: Update WALLPAPERS.md

on:
  push:
    paths:
      - 'images/**'

jobs:
  update-wallpapers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update WALLPAPERS.md
      run: |
        #!/bin/bash
        set -e

        # Define the images folder and the output markdown file
        IMAGES_FOLDER="images"
        WALLPAPERS_MD="docs/WALLPAPERS.md"

        # Start writing the markdown content
        echo "# Wallpapers" > $WALLPAPERS_MD
        echo "" >> $WALLPAPERS_MD
        echo "Here is a list of all wallpapers in the images folder:" >> $WALLPAPERS_MD
        echo "" >> $WALLPAPERS_MD

        # Add each image to the markdown content
        for image_file in $IMAGES_FOLDER/*; do
          if [[ -f "$image_file" ]]; then
            image_name=$(basename "$image_file")
            echo "![$image_name]($image_file)" >> $WALLPAPERS_MD
            echo "" >> $WALLPAPERS_MD
          fi
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/WALLPAPERS.md
        git commit -m 'Update WALLPAPERS.md with new images'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
